name = "FuncPipelines"
uuid = "9ed96fbb-10b6-44d4-99a6-7e2a3dc8861b"
authors = ["chengchingwen <adgjl5645@hotmail.com> and contributors"]
version = "0.2.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
